version: '3.8'

services:

  # ------------------------------------------------
  # 1. Staging: Redis (Temp Storage)
  # ------------------------------------------------
  redis:
    image: redis:alpine
    container_name: traffy-redis
    ports:
      - "6379:6379"
    networks:
      - traffy-network

  # ------------------------------------------------
  # 2. Kafka Manager: Zookeeper 
  # ------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: traffy-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - traffy-network

  # ------------------------------------------------
  # 3. Streaming: Kafka (Message Broker)
  # ------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: traffy-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - traffy-network

  spark-notebook:
      image: jupyter/pyspark-notebook:latest
      container_name: traffy-spark
      user: root 
      environment:
        - JUPYTER_ENABLE_LAB=yes
        - GRANT_SUDO=yes
      ports:
        - "8888:8888" 
        - "4040:4040"
      volumes:
        - ./:/home/jovyan/work 
      networks:
        - traffy-network
      # ⚠️ สำคัญ: ต้องไปตั้งค่าใน Docker Desktop > Settings > Resources ให้เกิน 4GB ด้วย
      deploy:
        resources:
          limits:
            memory: 4G

networks:
  traffy-network:
    driver: bridge


volumes:
  pg_data: